accum-grad: 4
adim: 256
aheads: 4
backend: pytorch
dlayers: 6
dropout-rate: 0.1
dunits: 2048
elayers: 12
epochs: 230
eunits: 2048
grad-clip: 5
lsm-weight: 0.1
model-module: espnet.nets.pytorch_backend.e2e_asr_transformer:E2E
mtlalpha: 0.3
opt: noam
patience: 2000
transformer-attn-dropout-rate: 0.0
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 1.0
transformer-warmup-steps: 25000
ctc_type: builtin
report-cer: true
report-wer: true
